install! 'cocoapods',
  :disable_input_output_paths => true,
  :warn_for_multiple_pod_sources => false,:generate_multiple_pod_projects => true

platform :ios, '10.0'
inhibit_all_warnings!

# only source it
source "git@github.com:DanboDuan/Test_Dislike_Specs.git"
source "git@github.com:DanboDuan/Test_Prefer_Specs.git"


require "cocoapods-prefer"

plugin 'cocoapods-unit-test',:names => ["TestExample"]
plugin 'cocoapods-prefer'

# dislike_source("Test_Dislike","git@github.com:DanboDuan/Test_Dislike_Specs.git")
prefer_source("Test_Prefer","git@github.com:DanboDuan/Test_Prefer_Specs.git")


target 'Example' do

  lock_source_with_url("git@github.com:DanboDuan/Test_Prefer_Specs.git") do
    prefer_source_pod 'AFNetworking'
  end

  lock_source_with_url("git@github.com:DanboDuan/Test_Dislike_Specs.git") do
    dislike_source_pod 'FMDB','~> 2.0'
  end

  pod 'Godzippa'
  pod 'XcodeCoverage'

  pod 'TestExample', :path => '../',:testspecs => ["Tests"]
end
