install! 'cocoapods',
  :disable_input_output_paths => true,
  :warn_for_multiple_pod_sources => false,:generate_multiple_pod_projects => true
platform :ios, '10.0'

# inhibit_all_warnings!

plugin 'cocoapods-unit-test',:names => ["TestExample","xx"]


target 'Example' do
  # pod 'XcodeCoverage', '>= 1.3.2'
  pod 'XcodeCoverage',:git => 'git@github.com:jonreid/XcodeCoverage.git'
  pod 'TestExample', :path => '../',:testspecs => ["Tests"]
end
